In [5]:
import pandas as pd
import numpy as np
import seaborn as sns

df = sns.load_dataset('penguins')
df.head(3)

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female

### One hot encoding with a single column

In [6]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
transformed = ohe.fit_transform(df['island'].values.reshape(-1, 1))

print(transformed.toarray())
print(ohe.categories_)
print(ohe.get_feature_names_out(['island']))

df[ohe.categories_[0]] = transformed.toarray()
df.head(3)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[array(['Biscoe', 'Dream', 'Torgersen'], dtype=object)]
['island_Biscoe' 'island_Dream' 'island_Torgersen']


species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   

   body_mass_g     sex  Biscoe  Dream  Torgersen  
0       3750.0    Male     0.0    0.0        1.0  
1       3800.0  Female     0.0    0.0        1.0  
2       3250.0  Female     0.0    0.0        1.0

### One hot encoding with a single column and column transformer

In [8]:
import seaborn as sns
from sklearn.compose import make_column_transformer

df = sns.load_dataset('penguins')

transformer = make_column_transformer(
    (OneHotEncoder(), ['island']), 
    remainder='passthrough'
)

transformed = transformer.fit_transform(df)
print(transformed)

trasformed_df = pd.DataFrame(transformed, columns=transformer.get_feature_names_out())
trasformed_df.head(3)

[[0.0 0.0 1.0 ... 181.0 3750.0 'Male']
 [0.0 0.0 1.0 ... 186.0 3800.0 'Female']
 [0.0 0.0 1.0 ... 195.0 3250.0 'Female']
 ...
 [1.0 0.0 0.0 ... 222.0 5750.0 'Male']
 [1.0 0.0 0.0 ... 212.0 5200.0 'Female']
 [1.0 0.0 0.0 ... 213.0 5400.0 'Male']]


onehotencoder__island_Biscoe onehotencoder__island_Dream  \
0                          0.0                         0.0   
1                          0.0                         0.0   
2                          0.0                         0.0   

  onehotencoder__island_Torgersen remainder__species  \
0                             1.0             Adelie   
1                             1.0             Adelie   
2                             1.0             Adelie   

  remainder__bill_length_mm remainder__bill_depth_mm  \
0                      39.1                     18.7   
1                      39.5                     17.4   
2                      40.3                     18.0   

  remainder__flipper_length_mm remainder__body_mass_g remainder__sex  
0                        181.0                 3750.0           Male  
1                        186.0                 3800.0         Female  
2                        195.0                 3250.0         Female

### One hot encoding with multiple columns and column transformer

In [9]:
import seaborn as sns
from sklearn.compose import make_column_transformer

df = sns.load_dataset('penguins')

print(df.isna().sum())
df = df.dropna()  # all NaN values must be dropped - if not NaN is assumed as one of category values (a unique value of the feature) 

transformer = make_column_transformer(
    (OneHotEncoder(), ['island', 'sex', 'species']), 
    remainder='passthrough'
)

transformed = transformer.fit_transform(df)
transformed_df = pd.DataFrame(transformed, columns=transformer.get_feature_names_out())
transformed_df.head(3)

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64


onehotencoder__island_Biscoe  onehotencoder__island_Dream  \
0                           0.0                          0.0   
1                           0.0                          0.0   
2                           0.0                          0.0   

   onehotencoder__island_Torgersen  onehotencoder__sex_Female  \
0                              1.0                        0.0   
1                              1.0                        1.0   
2                              1.0                        1.0   

   onehotencoder__sex_Male  onehotencoder__species_Adelie  \
0                      1.0                            1.0   
1                      0.0                            1.0   
2                      0.0                            1.0   

   onehotencoder__species_Chinstrap  onehotencoder__species_Gentoo  \
0                               0.0                            0.0   
1                               0.0                            0.0   
2                               0.0                            0.0   

   remainder__bill_length_mm  remainder__bill_depth_mm  \
0                       39.1                      18.7   
1                       39.5                      17.4   
2                       40.3                      18.0   

   remainder__flipper_length_mm  remainder__body_mass_g  
0                         181.0                  3750.0  
1                         186.0                  3800.0  
2                         195.0                  3250.0